# Generated by Django 5.2.6 on 2025-09-19 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('crop', models.CharField(blank=True, max_length=200)),
                ('farming_type', models.CharField(choices=[('traditional', 'Traditional'), ('hydroponics', 'Hydroponics')], default='traditional', max_length=50)),
                ('tank_capacity', models.FloatField(default=1000.0, help_text='Tank capacity in liters (used to compute water usage)')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('water_level', models.FloatField()),
                ('ph', models.FloatField()),
                ('light_intensity', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='irrigation.farmer')),
            ],
        ),
    ]
